concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "REL-RUNNNER"
  url = "http://192.168.0.102:4000/"
  id = 4
  token = "_uBAcPaZMEwLwBZmM35g"
  token_obtained_at = 2022-10-17T07:09:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  builds_dir = "./release"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]