image: alpine

before_script:
  - apk add npm
  - apk add git --no-cache
  - git --version

stages:
  - clone
  - build

clone repo:
  stage: clone
  script:
    - echo "Cloning Frontend Repo"
    # created folder for clone
    - mkdir workspace
    - cd workspace
    - pwd && ls
    - git clone https://gitlab.com/lowjiewei/tms-a3.git
    - pwd && ls
    - cd ./tms-a3/FE_src
    - pwd && ls
    - npm install
    - cd src
    - npm run dev
    - npm run build

  artifacts:
    paths:
      # saving the entire folder
      - ./workspace

build:
  stage: build
  script:
    - echo "Building Frontend Repo"
    - pwd
    # - cd tms-a3/FE_src

    # - npm install

