stages:
  - clone
  - build_and_publish
  - deploy

variables:
  GIT_CLONE_PATH: "./release/$CI_COMMIT_BRANCH"
  GIT_STRATEGY: none
  # CLONE_BRANCH: $BRANCH_NAME

clone_repo:
  stage: clone
  script:
    - echo "Cloning REL_BE_0_3_1"`
    - git clone --branch $CI_COMMIT_BRANCH http://192.168.0.102:4000/root/be.git C:/Users/commonuser/Desktop/release/$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/

build_website:
  stage: build_and_publish
  script:
    - pwd
    - cd C:\Users\commonuser\Desktop\release\$CI_COMMIT_BRANCH\build
    - ./build.sh
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/
  dependencies:
    - clone_repo

deploy_website:
  stage: deploy
  script:
    - cd C:\Users\commonuser\Desktop\release\$CI_COMMIT_BRANCH\deploy
    - ./deploy.ps1
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/
  dependencies:
    - build_website
